//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by batticfg.rc
//
#define IDD_COLOR                       101
#define IDD_BATTICFG_ABOUT              102
#define IDD_BATTICFG_GENERAL            103
#define IDD_BATTICFG_ADVANCED           104
#define IDD_BATTICFG_APPEARANCE         105
#define IDD_LICENSE                     107
#define IDR_MAINFRAME                   128
#define IDR_MAIN                        129
#define IDI_BATTI                       130
#define IDB_STOP                        132
#define IDB_PLAY                        133
#define IDR_CANCEL                      133
#define IDB_PLAY_HI                     134
#define IDB_STOP_HI                     135
#define IDS_BATTI                       200
#define IDS_OPTIONS                     201
#define IDS_BATTI_CONFIG                202
#define IDS_FOREGROUND                  203
#define IDS_BACKGROUND                  204
#define IDS_FRAME                       205
#define IDS_AC                          206
#define IDS_NO_ACTION                   207
#define IDS_OPEN_CONFIG                 208
#define IDS_LOW_FG                      209
#define IDS_LOW_BG                      210
#define IDS_CRITICAL_FG                 211
#define IDS_CRITICAL_BG                 212
#define IDS_CRITICAL_BIGGER_THAN_LOW    213
#define IDS_BATTERY_LOW                 214
#define IDS_BATTERY_CRITICAL            215
#define IDS_UNKNOWN                     216
#define IDS_CHARGING_STARTED            217
#define IDS_CHARGING_ENDS               218
#define IDS_CHARGING_FG                 219
#define IDS_CHARGING_BG                 220
#define IDS_POWEROFF_BIGGER_THAN_CRITICAL 222
#define IDS_SHOW_INFO                   223
#define IDS_POWER_OFF                   224
#define IDS_SELECT_COLOR                225
#define IDS_ABOUT                       226
#define IDC_HSFIELD                     900
#define IDC_LIGHTNESS                   901
#define IDC_COLOR                       902
#define IDC_HVALUE                      903
#define IDC_HSPIN                       904
#define IDC_SVALUE                      905
#define IDC_SSPIN                       906
#define IDC_LVALUE                      907
#define IDC_LSPIN                       908
#define IDC_RVALUE                      909
#define IDC_RSPIN                       910
#define IDC_GVALUE                      911
#define IDC_GSPIN                       912
#define IDC_BVALUE                      913
#define IDC_BSPIN                       914
#define IDC_C_COLOR2                    915
#define IDC_OPTIONS_LBL                 1000
#define IDC_CHARGE_INDICATOR            1001
#define IDC_BLINKING                    1002
#define IDC_ALWAYSONTOP                 1003
#define IDC_ACTION_ON_TAP_LBL           1004
#define IDC_TAP_ACTION                  1005
#define IDC_UPDATE_LBL                  1006
#define IDC_C_UPDATE_EVERY              1007
#define IDC_SECONDS                     1008
#define IDC_SECONDS_SPIN                1009
#define IDC_C_SECONDS                   1010
#define IDC_HOMEPAGE_LINK               1011
#define IDC_C_LEFT_MARGIN               1012
#define IDC_LEFTMARGIN                  1013
#define IDC_LEFTMARGIN_SPIN             1014
#define IDC_C_HEIGHT                    1015
#define IDC_HEIGHT                      1016
#define IDC_HEIGHT_SPIN                 1017
#define IDC_COLOR_LBL                   1018
#define IDC_COLOR_NAME                  1019
#define IDC_C_COLOR                     1020
#define IDC_CLR                         1021
#define IDC_HAS_FRAME                   1022
#define IDC_SOUNDS_LBL                  1023
#define IDC_SOUNDEVENTS                 1024
#define IDC_PLAYSOUND                   1025
#define IDC_SOUNDFILE                   1026
#define IDC_LEVELS_LBL                  1027
#define IDC_C_LOW_LEVEL                 1028
#define IDC_LOW                         1029
#define IDC_LOW_SPIN                    1030
#define IDC_C_PERCENT2                  1031
#define IDC_C_CRITICAL_LEVEL            1032
#define IDC_CRITICAL                    1033
#define IDC_CRITICAL_SPIN               1034
#define IDC_C_PERCENT                   1035
#define IDC_C_POWEROFF_LEVEL            1036
#define IDC_POWEROFF                    1037
#define IDC_POWEROFF_SPIN               1038
#define IDC_C_PERCENT5                  1039
#define IDC_STEPS                       1073
#define IDC_SYSTRAY_ICON                1074
#define IDC_PLAY                        1075
#define IDC_STOP                        1076
#define IDC_GRADIENT                    1077
#define IDC_LICENSE                     1078
#define IDS_CAP_CANCEL                  32773
#define IDS_CAP_MENUITEM32774           32775
#define IDS_CAP_ABOUT                   32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
